---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dynamodb-local
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dynamodb-local
    spec:
      containers:
      - name: dynamodb-local
        image: dynamodb-local:experimental
        ports:
          - containerPort: 8000
      restartPolicy: Always
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: streamdigest
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: streamdigest
    spec:
      containers:
      - name: streamdigest
        image: streamdigest:experimental
        ports:
          - containerPort: 15000
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: streamdigest
  name: streamdigest
spec:
  type: NodePort
  ports:
  - port: 15000
  selector:
    app: streamdigest
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: streamdigest-docs
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: streamdigest-docs
    spec:
      containers:
      - name: streamdigest-docs
        image: streamdigestdocs:experimental
        ports:
          - containerPort: 8080
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: streamdigest-docs
  name: streamdigest-docs
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: streamdigest-docs