---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: streamdigest
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: streamdigest
    spec:
      containers:
      - name: streamdigest
        image: streamdigest:experimental
        ports:
        - containerPort: 15000
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: streamdigest
  name: streamdigest
spec:
  type: NodePort
  ports:
  - port: 15000
  selector:
    app: streamdigest
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: streamdigest-docs
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: streamdigest-docs
    spec:
      containers:
      - name: streamdigest-docs
        image: streamdigestdocs:experimental
        ports:
          - containerPort: 8080
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: streamdigest-docs
  name: streamdigest-docs
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: streamdigest-docs