---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: streamdigest
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: streamdigest
    spec:
      containers:
      - name: streamdigest
        image: streamdigest:experimental
        ports:
          - containerPort: 15000
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: streamdigest
  name: streamdigest
spec:
  type: NodePort
  ports:
  - port: 15000
  selector:
    app: streamdigest