---
  swagger: "2.0"
  info:
    description: A Digest for a livestream
    title: Stream Digest
    version: 0.1.0
  schemes:
  - http
  consumes:
  - application/json
  produces:
  - application/json
  paths:
    /clip/{streamerId}:
      post:
        tags:
          - digest
        summary: "add a clip to a streamer's digest by their streamer id"
        description: "returns a response describing whether the attempted save was successful"
        operationId: addClipByStreamerId
        parameters:
          - name: "streamerId"
            in: "path"
            description: "ID of the streamer"
            required: true
            type: "integer"
            format: "uint64"
          - name: "Clip"
            in: "body"
            description: "data on the clip to be added to the digest"
            required: true
            schema:
              $ref: "#/definitions/Clip"
        responses:
          201:
            description: successfully added clip
          default:
            description: unexpected error
            schema:
              $ref: "#/definitions/UnexpectedError"
    /digest/{streamerId}:
      get:
        tags:
          - digest
        summary: "find a digest by streamer id"
        description: "returns a digest of a given streamer"
        operationId: getDigestByStreamerId
        parameters:
          - name: "streamerId"
            in: "path"
            description: "ID of the streamer"
            required: true
            type: "integer"
            format: "uint64"
        responses:
          200:
            description: get splash message
            schema:
              $ref: "#/definitions/Digest"
          default:
            description: unexpected error
            schema:
              $ref: "#/definitions/UnexpectedError"
  definitions:
    Digest:
      type: "array"
      items:
        type: string
    Clip:
      type: "object"
      required:
        - url
      properties:
        url:
          type: string
          readOnly: true
          pattern: '^(https:\/\/www\.|https:\/\/)?neatclip.com/clip/[a-zA-Z0-9]{8}$'
    UnexpectedError:
      type: "object"
      properties:
        message:
          type: "string"
