---
  swagger: "2.0"
  info:
    description: A Digest for a livestream
    title: Stream Digest
    version: 0.1.0
  schemes:
  - http
  consumes:
  - application/json
  produces:
  - application/json
  paths:
    /:
      get:
        tags:
          - splash
        operationId: getSplash
        responses:
          200:
            description: get splash message
            schema:
              $ref: "#/definitions/Splash"
          default:
            description: unexpected error
            schema:
              $ref: "#/definitions/UnexpectedError"
  definitions:
    Splash:
      type: "object"
      properties:
        message:
          type: "string"
    UnexpectedError:
      type: "object"
      properties:
        message:
          type: "string"
