---
  swagger: "2.0"
  info:
    description: A Digest for a livestream
    title: Stream Digest
    version: 0.1.0
  schemes:
  - http
  consumes:
  - application/json
  produces:
  - application/json
  paths:
    /digest/{streamerId}:
      get:
        tags:
          - digest
        summary: "find a digest by streamer id"
        description: "returns a digest of a given streamer"
        operationId: getDigestByStreamerId
        parameters:
          - name: "streamerId"
            in: "path"
            description: "ID of the streamer"
            required: true
            type: "integer"
            format: "uint64"
        responses:
          200:
            description: get splash message
            schema:
              $ref: "#/definitions/Digest"
          default:
            description: unexpected error
            schema:
              $ref: "#/definitions/UnexpectedError"
  definitions:
    Digest:
      type: "object"
      properties:
        message:
          type: "string"
    UnexpectedError:
      type: "object"
      properties:
        message:
          type: "string"
