// Code generated by go-swagger; DO NOT EDIT.

package restapi

import (
	"crypto/tls"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/tylerb/graceful"

	"github.com/snuffalo/streamDigest/restapi/operations"
	"github.com/snuffalo/streamDigest/restapi/operations/digest"
	"github.com/snuffalo/streamDigest/impl"
	"github.com/snuffalo/streamDigest/models"
	"strconv"
	"database/sql"
	"log"
	"fmt"
	_ "github.com/go-sql-driver/mysql"
)

// This file is safe to edit. Once it exists it will not be overwritten

//go:generate swagger generate server --target .. --name streamdigest --spec ../swagger.yml

const BASE_TEN = 10

func configureFlags(api *operations.StreamdigestAPI) {
	// api.CommandLineOptionsGroups = []swag.CommandLineOptionsGroup{ ... }
}

func configureAPI(api *operations.StreamdigestAPI) http.Handler {
	log.Printf("Configuring streamdigest...")
	// configure the api here
	api.ServeError = errors.ServeError

	// Set your custom logger if needed. Default one is log.Printf
	// Expected interface func(string, ...interface{})
	//
	// Example:
	// api.Logger = log.Printf

	log.Print("Connecting to Mysql server...")
	db := connectToMysql()
	log.Print("Connected to Mysql server.")

	api.JSONConsumer = runtime.JSONConsumer()

	api.JSONProducer = runtime.JSONProducer()

	api.DigestGetDigestByStreamerIDHandler = digest.GetDigestByStreamerIDHandlerFunc(func(params digest.GetDigestByStreamerIDParams) middleware.Responder {
		return digest.NewGetDigestByStreamerIDOK().WithPayload(impl.GetDigestByStreamerId(params.StreamerID))
	})

	api.DigestAddClipByStreamerIDHandler = digest.AddClipByStreamerIDHandlerFunc(func(params digest.AddClipByStreamerIDParams) middleware.Responder{
		var success = impl.AddClipToDigestByStreamerId(params.Clip, params.StreamerID, db)
		if success {
			return digest.NewAddClipByStreamerIDCreated()
		} else {
			return digest.NewAddClipByStreamerIDConflict().WithPayload(&models.DuplicateClip{Message: "Duplicate clip \"" + params.Clip.URL + "\" for streamer id \"" + strconv.FormatUint(params.StreamerID, BASE_TEN) + "\"."})
		}
	})

	api.ServerShutdown = func() {}

	return setupGlobalMiddleware(api.Serve(setupMiddlewares))
}

// The TLS configuration before HTTPS server starts.
func configureTLS(tlsConfig *tls.Config) {
	// Make all necessary changes to the TLS configuration here.
}

// As soon as server is initialized but not run yet, this function will be called.
// If you need to modify a config, store server instance to stop it individually later, this is the place.
// This function can be called multiple times, depending on the number of serving schemes.
// scheme value will be set accordingly: "http", "https" or "unix"
func configureServer(s *graceful.Server, scheme, addr string) {
}

// The middleware configuration is for the handler executors. These do not apply to the swagger.json document.
// The middleware executes after routing but before authentication, binding and validation
func setupMiddlewares(handler http.Handler) http.Handler {
	return handler
}

// The middleware configuration happens before anything, this middleware also applies to serving the swagger.json document.
// So this is a good place to plug in a panic handling middleware, logging and metrics
func setupGlobalMiddleware(handler http.Handler) http.Handler {
	return handler
}

func connectToMysql() *sql.DB {
	//Open doesn't actually try a connection
	db, err := sql.Open("mysql", "root:password@tcp(mysql:3306)/streamDigest")
	if (err == nil) {
		_, err := db.Exec("USE streamDigest;")
		if err == nil {
			return db
		}
		fmt.Printf("%s", err.Error())
		panic(err)
	}
	fmt.Printf("%s", err.Error())
	panic(err)
}
